// Generated by https://quicktype.io

namespace forex_app_trader.Models
{
    using System;
    using System.Text.Json.Serialization;


    public partial class ForexSessionInDTO
    {
       
        [JsonPropertyName("sessionUser")]
        public SessionUserInDTO SessionUser { get; set; }

        [JsonPropertyName("startDate")]
        public string StartDate { get; set; }

        [JsonPropertyName("endDate")]
        public string EndDate { get; set; }

        [JsonPropertyName("currentTime")]
        public string CurrentTime { get; set; }

        [JsonPropertyName("lastUpdatedTime")]
        public string LastUpdatedTime { get; set; }

        [JsonPropertyName("sessionType")]
        public SessionType SessionType { get; set; }

        [JsonPropertyName("strategy")]
        public StrategyInDTO Strategy { get; set; }

        [JsonPropertyName("id")]
        public string Id { get; set; }

        [JsonPropertyName("elapsedTime")]
        public string ElapsedTime { get; set; }

        [JsonPropertyName("beginSessionTime")]
        public string BeginSessionTime { get; set; }

        [JsonPropertyName("endSessionTime")]
        public string EndSessionTime { get; set; }

        [JsonPropertyName("experimentId")]
        public string ExperimentId { get; set; }

        [JsonPropertyName("percentComplete")]
        public double PercentComplete { get; set; }
    }

    public partial class SessionType
    {
        static readonly string[] sessionTypes = {"live","test"};
        [JsonPropertyName("index")]
        public int Index { get; set; }

        public string Value => sessionTypes[Index];
    }

    public partial class SessionUserInDTO
    {
        [JsonPropertyName("Accounts")]
        public AccountsInDTO Accounts { get; set; }
    }

    public partial class AccountsInDTO
    {
        [JsonPropertyName("primary")]
        public AccountInDTO Primary { get; set; }

        [JsonPropertyName("secondary")]
        public AccountInDTO Secondary { get; set; }
    }

    public partial class AccountInDTO
    {
        [JsonPropertyName("id")]
        public string Id { get; set; }

        [JsonPropertyName("cash")]
        public double Cash { get; set; }

        [JsonPropertyName("realizedPL")]
        public double RealizedPL { get; set; }

        [JsonPropertyName("Margin")]
        public double Margin { get; set; }

        [JsonPropertyName("MarginRatio")]
        public double MarginRatio { get; set; }

        [JsonPropertyName("idcount")]
        public long Idcount { get; set; }

        [JsonPropertyName("Trades")]
        public TradeInDTO[] Trades { get; set; }

        [JsonPropertyName("closedTrades")]
        public TradeInDTO[] ClosedTrades { get; set; }

        [JsonPropertyName("orders")]
        public OrderInDTO[] Orders { get; set; }

        [JsonPropertyName("balanceHistory")]
        public BalanceHistoryInDTO[] BalanceHistory { get; set; }
    }

    public partial class BalanceHistoryInDTO
    {
        [JsonPropertyName("date")]
        public string Date { get; set; }

        [JsonPropertyName("amount")]
        public double Amount { get; set; }
    }

    public partial class TradeInDTO
    {
        [JsonPropertyName("pair")]
        public string Pair { get; set; }

        [JsonPropertyName("units")]
        public long Units { get; set; }

        [JsonPropertyName("id")]
        public long Id { get; set; }

        [JsonPropertyName("openDate")]
        public string OpenDate { get; set; }

        [JsonPropertyName("closeDate")]
        public string? CloseDate { get; set; }

        [JsonPropertyName("openPrice")]
        public double OpenPrice { get; set; }

        [JsonPropertyName("closePrice")]
        public double ClosePrice { get; set; }

        [JsonPropertyName("stopLoss")]
        public double StopLoss { get; set; }

        [JsonPropertyName("takeProfit")]
        public double TakeProfit { get; set; }

        [JsonPropertyName("long")]
        public bool Long { get; set; }

        [JsonPropertyName("init")]
        public bool Init { get; set; }
    }

    public partial class OrderInDTO
    {
        [JsonPropertyName("trade")]
        public TradeInDTO Trade { get; set; }

        [JsonPropertyName("triggerprice")]
        public double Triggerprice { get; set; }

        [JsonPropertyName("expired")]
        public bool Expired { get; set; }

        [JsonPropertyName("above")]
        public bool Above { get; set; }
    }

    public partial class StrategyInDTO
    {
        [JsonPropertyName("ruleName")]
        public string RuleName { get; set; }

        [JsonPropertyName("position")]
        public string Position { get; set; }

        [JsonPropertyName("window")]
        public long Window { get; set; }

        [JsonPropertyName("units")]
        public long Units { get; set; }

        [JsonPropertyName("stopLoss")]
        public double StopLoss { get; set; }

        [JsonPropertyName("takeProfit")]
        public double TakeProfit { get; set; }
    }


}
