version: '3'

services:
  forex-app-service:
    image: 127.0.0.1:5000/forex-app-service
    build: .
    ports:
      - "124:80"
    depends_on:
      - mongo
      - forexapp
      - forex-experiment
    environment:
    - ASPNETCORE_ENVIRONMENT='Production'
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
  forexapp:
    image: 127.0.0.1:5000/forexapp
    ports:
      - "122:80"
    depends_on:
      - mongo
  strategyapp:
    image: 127.0.0.1:5000/strategyapp
    depends_on:
      - mongo
  importdatafromcloudapp:
      image: 127.0.0.1:5000/importdatafromcloudapp
      depends_on:
        - mongo
  forex-experiment:
    image: 127.0.0.1:5000/forex-experiment
    ports:
      - "8081:80"
    depends_on:
      - mongo
volumes:
  mongodata: