apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: basic-ingress
  annotations:
    traefik.frontend.rule.type: PathPrefixStrip
spec:
    rules:
        - http:
            paths:
            - path: /
              backend:
                serviceName: forex
                servicePort: 80    
            - path: /service
              backend:
                serviceName: forex-app-service-frontend
                servicePort: 80
            - path: /strategy
              backend:
                serviceName: trade
                servicePort: 80