// Generated by https://quicktype.io

using System.Text.Json.Serialization;
namespace forex_app_service.Models
{

    public  class ForexRealTradeDto
    {
        [JsonPropertyName("order")]
        public RealOrder Order { get; set; }
    }

    public  class RealOrder
    {
        [JsonPropertyName("units")]
        public string Units { get; set; }

        [JsonPropertyName("instrument")]
        public string Instrument { get; set; }

        [JsonPropertyName("timeInForce")]
        public string TimeInForce { get; set; }

        [JsonPropertyName("type")]
        public string Type { get; set; }

        [JsonPropertyName("positionFill")]
        public string PositionFill { get; set; }

        [JsonPropertyName("stopLossOnFill")]
        public OnFill StopLossOnFill { get; set; }

        [JsonPropertyName("takeProfitOnFill")]
        public OnFill TakeProfitOnFill { get; set; }
    }

    public class OnFill
    {
        [JsonPropertyName("price")]
        public string Price { get; set; }
    }

}
